"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000";
type Ticket={id:string;category:string;message:string;status:string;createdAt:string};
export default function SupportPage(){
 const cats=["Care request","Medical document","Account & privacy","Technical issue","Other"];
 const[category,setCategory]=useState(cats[0]),[message,setMessage]=useState(""),[tickets,setTickets]=useState<Ticket[]>([]),[error,setError]=useState(""),[sent,setSent]=useState(false);
 async function load(){const r=await fetch(API+"/v1/support/tickets",{credentials:"include"});if(!r.ok){setError("Sign in to manage support requests.");return}setTickets(await r.json())}
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[]);
 async function submit(){setError("");const r=await fetch(API+"/v1/support/tickets",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({category,message})});if(!r.ok){setError("Unable to send your request.");return}setMessage("");setSent(true);void load()}
 return <main style={{maxWidth:980,margin:"auto",padding:"48px 24px",fontFamily:"Inter,system-ui,sans-serif",color:"#172334"}}><p style={{color:"#64748b",fontWeight:800,letterSpacing:".12em",fontSize:12}}>CAREBRIDGE · SUPPORT</p><h1 style={{fontSize:42,margin:"8px 0"}}>How can we help?</h1><p style={{color:"#64748b",fontSize:17}}>Create and track a support request from your CareBridge account.</p>{error&&<div style={{marginTop:18,padding:14,borderRadius:14,background:"#fff7ed"}}>{error}</div>}{sent&&<div style={{marginTop:18,padding:14,borderRadius:14,background:"#ecfdf5",color:"#166534"}}>Request received. Track its status below.</div>}<section style={{marginTop:28,padding:26,border:"1px solid #e2e8f0",borderRadius:24}}><label style={{display:"grid",gap:7,fontWeight:700}}>Topic<select value={category} onChange={e=>setCategory(e.target.value)} style={{padding:13,border:"1px solid #cbd5e1",borderRadius:12}}>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label style={{display:"grid",gap:7,fontWeight:700,marginTop:16}}>Message<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={7} placeholder="Tell us what you need help with..." style={{padding:13,border:"1px solid #cbd5e1",borderRadius:12}}/></label><button disabled={message.trim().length<5} onClick={submit} style={{marginTop:16,padding:"13px 18px",border:0,borderRadius:13,background:"#1672b8",color:"white",fontWeight:800}}>Send support request</button></section><section style={{marginTop:24,padding:26,border:"1px solid #e2e8f0",borderRadius:24}}><h2>Your requests</h2>{tickets.length===0?<p style={{color:"#64748b"}}>No support requests yet.</p>:tickets.map(t=><article key={t.id} style={{padding:"15px 0",borderTop:"1px solid #eef2f7"}}><div style={{display:"flex",justifyContent:"space-between"}}><b>{t.category}</b><span style={{fontSize:12,fontWeight:800}}>{t.status}</span></div><p>{t.message}</p><small style={{color:"#94a3b8"}}>{new Date(t.createdAt).toLocaleString()}</small></article>)}</section></main>;
}
