"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000";
type Doctor={id:string;name:string;bio:string;location:string;experienceYears:number;consultationPriceUsd:number;expertise:any;status:string;isVerified:boolean;specialty?:{name:string}};
type Credential={id:string;type:string;licenseNumber:string;jurisdiction:string;documentName?:string;status:string;createdAt:string};
export default function DoctorProfile(){
 const[doctor,setDoctor]=useState<Doctor|null>(null);const[credentials,setCredentials]=useState<Credential[]>([]);const[bio,setBio]=useState("");const[location,setLocation]=useState("");const[price,setPrice]=useState("");const[expertise,setExpertise]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
 async function load(){try{const[d,c]=await Promise.all([fetch(API+"/v1/doctor/me",{credentials:"include"}),fetch(API+"/v1/doctor/credentials",{credentials:"include"})]);if(!d.ok||!c.ok)throw Error();const dv=await d.json();setDoctor(dv);setBio(dv.bio??"");setLocation(dv.location??"");setPrice(String(dv.consultationPriceUsd??""));setExpertise(Array.isArray(dv.expertise)?dv.expertise.join(", "):"");setCredentials(await c.json())}catch{setMessage("Sign in as a doctor to manage your profile.")}finally{setLoading(false)}}
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{void load()},[]);
async function save(){const r=await fetch(API+"/v1/doctor/me/profile",{method:"PATCH",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({bio,location,consultationPriceUsd:Number(price),expertise:expertise.split(",").map(x=>x.trim()).filter(Boolean)})});if(r.ok){setDoctor(await r.json());setMessage("Profile saved.")}else setMessage("Unable to save profile.")}
if(loading)return <main className="doctor-page">Loading profile…</main>;
return <main className="doctor-page"><div className="doctor-container"><a href="/dashboard">← Dashboard</a><header className="doctor-header"><div><p className="eyebrow">CAREBRIDGE · PROVIDER PROFILE</p><h1>{doctor?.name??"Doctor profile"}</h1><p>{doctor?.specialty?.name??"Specialist"} · {doctor?.experienceYears??0} years experience</p></div><div className={doctor?.isVerified?"status verified":"status pending"}>{doctor?.isVerified?"VERIFIED":"PENDING VERIFICATION"}</div></header><section className="doctor-card"><h2>Professional profile</h2><label>Biography<textarea value={bio} onChange={e=>setBio(e.target.value)} rows={6}/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Expertise <span>comma separated</span><input value={expertise} onChange={e=>setExpertise(e.target.value)}/></label><label>Consultation price (USD)<input type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)}/></label><button onClick={save}>Save profile</button>{message&&<p className="message">{message}</p>}</section><section className="doctor-card"><h2>Verification credentials</h2><p>Credential status is controlled by CareBridge administration.</p>{credentials.length===0?<p>No credentials submitted.</p>:credentials.map(c=><div className="credential" key={c.id}><div><b>{c.type}</b><span>{c.licenseNumber} · {c.jurisdiction}</span>{c.documentName&&<span>{c.documentName}</span>}</div><strong>{c.status}</strong></div>)}</section></div><style>{`.doctor-page{min-height:100vh;background:#f6f9fc;color:#142235;padding:42px 24px;font-family:Inter,system-ui,sans-serif}.doctor-container{max-width:950px;margin:auto}.doctor-page a{color:#1672b8;text-decoration:none}.doctor-header{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin:24px 0}.eyebrow{font-size:12px;font-weight:800;letter-spacing:.12em;color:#64788d}.doctor-header h1{font-size:42px;margin:8px 0}.doctor-header p{color:#64788d}.status{padding:9px 13px;border-radius:999px;font-size:12px;font-weight:800}.status.verified{background:#e8f7ef;color:#17653f}.status.pending{background:#fff5e6;color:#9a5b11}.doctor-card{background:#fff;border:1px solid #dfe8f0;border-radius:24px;padding:26px;margin-top:20px;display:grid;gap:16px}.doctor-card label{display:grid;gap:7px;font-weight:700}.doctor-card label span{font-size:12px;font-weight:400;color:#718398}.doctor-card input,.doctor-card textarea{font:inherit;padding:12px;border:1px solid #cbd9e5;border-radius:12px}.doctor-card button{justify-self:start;padding:12px 18px;border:0;border-radius:12px;background:#1672b8;color:#fff;font-weight:800}.message{padding:12px;border-radius:12px;background:#edf7f3;color:#17653f}.credential{display:flex;justify-content:space-between;gap:20px;padding:15px 0;border-top:1px solid #eef2f7}.credential span{display:block;color:#718398;font-size:13px;margin-top:4px}`}</style></main>;
}