"use client";
import {useEffect,useState} from "react";
import {getDoctors,getCredentials,reviewCredential,getPatients,getAppointments,type AdminDoctor,type AdminCredential,type AdminPatient,type AdminAppointment} from "../../lib/api";
export default function Operations(){
 const[doctors,setDoctors]=useState<AdminDoctor[]>([]);const[patients,setPatients]=useState<AdminPatient[]>([]);const[appointments,setAppointments]=useState<AdminAppointment[]>([]);const[selected,setSelected]=useState<AdminDoctor|null>(null);const[credentials,setCredentials]=useState<AdminCredential[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState("");
 async function load(){try{const[d,p,a]=await Promise.all([getDoctors(),getPatients(),getAppointments()]);setDoctors(d);setPatients(p);setAppointments(a)}catch(e){setError(e instanceof Error?e.message:"Unable to load operations.")}}
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[]);
 async function selectDoctor(d:AdminDoctor){setSelected(d);try{setCredentials(await getCredentials(d.id))}catch{setError("Unable to load credentials.")}}
 async function review(id:string,status:"APPROVED"|"REJECTED"){setBusy(id);try{await reviewCredential(id,status);if(selected)setCredentials(await getCredentials(selected.id))}catch(e){setError(e instanceof Error?e.message:"Credential review failed.")}finally{setBusy("")}}
 const name=(p:AdminPatient)=>[p.firstName,p.lastName].filter(Boolean).join(" ")||"Patient";
 return <main style={{minHeight:"100vh",background:"#f7f9fc",padding:"40px 24px",fontFamily:"Inter,system-ui,sans-serif",color:"#172334"}}><div style={{maxWidth:1200,margin:"auto"}}><a href="/dashboard" style={{color:"#1672b8"}}>← Operations center</a><p style={{fontSize:12,fontWeight:800,letterSpacing:".12em",color:"#64748b",marginTop:28}}>CAREBRIDGE · ADMIN CONTROL</p><h1>Operational management</h1><p style={{color:"#64748b"}}>Review providers, inspect patients and monitor appointment activity.</p>{error&&<div style={{padding:14,background:"#fff7ed",borderRadius:12}}>{error}</div>}<div style={{display:"grid",gridTemplateColumns:"1.1fr .9fr",gap:20,marginTop:26}}><section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:22,padding:22}}><h2>Provider credentials</h2>{doctors.map(d=><button key={d.id} onClick={()=>selectDoctor(d)} style={{display:"block",width:"100%",textAlign:"left",padding:14,border:0,borderTop:"1px solid #eef2f7",background:selected?.id===d.id?"#f0f7fc":"white"}}><b>{d.name}</b><div style={{color:"#718096"}}>{d.specialty.name} · {d.isVerified?"Verified":"Pending"} · {d.location}</div></button>)}{selected&&<div style={{marginTop:18,padding:18,borderRadius:16,background:"#f8fafc"}}><h3>{selected.name} credentials</h3>{credentials.length===0?<p>No credentials.</p>:credentials.map(c=><div key={c.id} style={{padding:"12px 0",borderTop:"1px solid #e2e8f0"}}><b>{c.type}</b><div style={{fontSize:13,color:"#64748b"}}>{c.licenseNumber} · {c.jurisdiction} · {c.status}</div>{c.status==="PENDING"&&<div style={{display:"flex",gap:8,marginTop:8}}><button disabled={busy===c.id} onClick={()=>review(c.id,"APPROVED")}>Approve</button><button disabled={busy===c.id} onClick={()=>review(c.id,"REJECTED")}>Reject</button></div>}</div>)}</div>}</section><section style={{background:"white",border:"1px solid #e2e8f0",borderRadius:22,padding:22}}><h2>Patients</h2>{patients.slice(0,15).map(p=><div key={p.id} style={{padding:"12px 0",borderTop:"1px solid #eef2f7"}}><b>{name(p)}</b><div style={{fontSize:13,color:"#64748b"}}>{p.user.email} · {p.country} · {p.user.status}</div></div>)}{!patients.length&&<p>No patients.</p>}</section></div><section style={{marginTop:20,background:"white",border:"1px solid #e2e8f0",borderRadius:22,padding:22}}><h2>Appointment operations</h2><div style={{display:"grid",gap:8}}>{appointments.slice(0,20).map(a=><div key={a.id} style={{display:"grid",gridTemplateColumns:"1.2fr 1.2fr 1fr 1fr",gap:12,padding:13,borderTop:"1px solid #eef2f7"}}><span>{name(a.patient)} · {a.patient.country}</span><span>{a.doctor.name} · {a.doctor.specialty.name}</span><span>{new Date(a.scheduledAt).toLocaleString()}</span><b>{a.consultation?.status??a.status}</b></div>)}{!appointments.length&&<p>No appointments.</p>}</div></section></div></main>